### ISSUE TITLE
ProcessLogItem (initialise/shutdownAll timing?)

### ISSUE THREAD

**Issue by StefanBertels** [louthy/echo-process#55]
I got
```
ProcessLogItem: 13:43.50.690 Error
You must call one of the  ProcessConfig.initialiseXXX functions

   at Echo.ActorContext.get_DefaultSystem()
   at Echo.ActorContext.System(SystemName system)
   at Echo.ActorContext.System(ProcessId pid)
   at Echo.LocalScheduler.ProcessActions()
```

with this code:
```
 static void Main(string[] args)
        {
            ProcessSystemLog.Subscribe(processLogItem => Console.WriteLine($"ProcessLogItem: {processLogItem}"));
            ProcessConfig.initialise();
            // var dummy = spawn<Unit,string>("bla", () => unit, (state, inbox) => state);
            Process.shutdownAll();
            Console.ReadKey();
        }
```

Probably minor issue. Found this because of a somewhat related issue (#56).

I thought subscribing to ProcessSystemLog is a good idea to catch any hidden bugs (like exceptions in actors' dispose functions). Should ProessSystemLog be a reliable source (i.e. error items are indicators of real errors)?

**Comment by louthy** [comment]
Released in 2.0.74-beta
